### ISSUE TITLE
Illegal byte sequence

### ISSUE THREAD

**Issue by vzikmund** [cardinalby/phpContentDisposition#3]
Hello, 
when I install your package via Composer, an error occurs: 

> error:  cannot create /path/to/my_project/vendor/composer/81eca07a/cardinalby-phpContentDisposition-8fc6f94/tests/browser_download/+�.txt
        Illegal byte sequence

I think it is caused by the weirdly named txt file 

![image](https://github.com/cardinalby/phpContentDisposition/assets/85373369/c1222054-0ef6-425a-99a0-3c417f6ac834)

**Comment by cardinalby** [comment]
Hi! Thank you for reporting!

I use macOS for development and didn't notice the problem after I added this file for tests. 
I removed the file and also tried to remove all unnecessary files from the package.

Please check `1.1.1` version

**Comment by vzikmund** [comment]
Yup, that solved my problem. Thank you for such a prompt response! 🚀
